In [199]:
from rdkit import Chem
from rdkit.Chem import Draw
from rdkit.Chem import rdDetermineBonds
from rdkit.Chem.Draw import IPythonConsole
from openff.toolkit import Molecule, Topology, ForceField
from openff.interchange import Interchange
from openff.units import unit
from openff.units.openmm import from_openmm, to_openmm
import openmm
import numpy as np
import sys
from pdb_wizard import PBC
import random
from copy import deepcopy
import scipy
import itertools

In [200]:
mol = Chem.MolFromXYZFile('./HKUST-1.xyz')

rdDetermineBonds.DetermineConnectivity(mol)
# IPythonConsole.drawMol3D(mol)

In [201]:
editable = Chem.EditableMol(mol)
# No kill like over kill
METALS = [3, 4, 11, 12, 13, 19, 20, 21, 22, 23, 24, 25 ,26, 27, 28, 29, 30, 31, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]

for bond in mol.GetBonds():
    a1 = bond.GetBeginAtom()
    a1_idx = bond.GetBeginAtomIdx()
    a2 = bond.GetEndAtom()
    a2_idx = bond.GetEndAtomIdx()
    if a1.GetAtomicNum() in METALS or a2.GetAtomicNum() in METALS:
        editable.RemoveBond(a1_idx, a2_idx)
    
# IPythonConsole.drawMol3D(editable.GetMol())

In [202]:
# You could change sanitizeFrags to True, but I doubt it's necessary
frags = Chem.GetMolFrags(editable.GetMol(), asMols=True, sanitizeFrags=True)
for frag in frags:
    if frag.GetNumAtoms() == 1:
        charge = 2
    else:
        charge = -3
    rdDetermineBonds.DetermineBonds(frag, charge=charge)

In [203]:
mols = [Molecule.from_rdkit(frag) for frag in frags]

In [204]:
for mol in mols:
    if mol.to_smiles() == '[Cu]':
        mol.atom(0).formal_charge = 2

In [205]:
def append_system(existing_system, system_to_append, cutoff, index_map=None):
    """Appends a system object onto the end of an existing system.

    Parameters
    ----------
    existing_system: openmm.System, optional
        The base system to extend.
    system_to_append: openmm.System
        The system to append.
    cutoff: openff.evaluator.unit.Quantity
        The nonbonded cutoff
    index_map: dict of int and int, optional
        A map to apply to the indices of atoms in the `system_to_append`.
        This is predominantly to be used when the ordering of the atoms
        in the `system_to_append` does not match the ordering in the full
        topology.
    """
    supported_force_types = [
        openmm.HarmonicBondForce,
        openmm.HarmonicAngleForce,
        openmm.PeriodicTorsionForce,
        openmm.NonbondedForce,
        openmm.RBTorsionForce,
        openmm.CustomNonbondedForce,
        openmm.CustomBondForce,
    ]

    number_of_appended_forces = 0
    index_offset = existing_system.getNumParticles()

    # Create an index map if one is not provided.
    if index_map is None:
        index_map = {i: i for i in range(system_to_append.getNumParticles())}

    # Append the particles.
    for index in range(system_to_append.getNumParticles()):
        index = index_map[index]
        existing_system.addParticle(system_to_append.getParticleMass(index))

    # Append the constraints
    for index in range(system_to_append.getNumConstraints()):
        index_a, index_b, distance = system_to_append.getConstraintParameters(index)

        index_a = index_map[index_a]
        index_b = index_map[index_b]

        existing_system.addConstraint(
            index_a + index_offset, index_b + index_offset, distance
        )

    # Validate the forces to append.
    for force_to_append in system_to_append.getForces():
        if type(force_to_append) in supported_force_types:
            continue

        raise ValueError(
            f"The system contains an unsupported type of "
            f"force: {type(force_to_append)}."
        )

    # Append the forces.
    for force_to_append in system_to_append.getForces():
        existing_force = None

        for force in existing_system.getForces():
            if type(force) not in supported_force_types:
                raise ValueError(
                    f"The existing system contains an unsupported type "
                    f"of force: {type(force)}."
                )

            if type(force_to_append) is not type(force):
                continue

            if isinstance(
                force_to_append, openmm.CustomNonbondedForce
            ) or isinstance(force_to_append, openmm.CustomBondForce):
                if force_to_append.getEnergyFunction() != force.getEnergyFunction():
                    continue

            existing_force = force
            break

        if existing_force is None:
            if isinstance(force_to_append, openmm.CustomNonbondedForce):
                existing_force = openmm.CustomNonbondedForce(
                    force_to_append.getEnergyFunction()
                )
                existing_force.setCutoffDistance(cutoff)
                existing_force.setNonbondedMethod(
                    openmm.CustomNonbondedForce.CutoffPeriodic
                )
                for index in range(force_to_append.getNumGlobalParameters()):
                    existing_force.addGlobalParameter(
                        force_to_append.getGlobalParameterName(index),
                        force_to_append.getGlobalParameterDefaultValue(index),
                    )
                for index in range(force_to_append.getNumPerParticleParameters()):
                    existing_force.addPerParticleParameter(
                        force_to_append.getPerParticleParameterName(index)
                    )
                existing_system.addForce(existing_force)

            elif isinstance(force_to_append, openmm.CustomBondForce):
                existing_force = openmm.CustomBondForce(
                    force_to_append.getEnergyFunction()
                )
                for index in range(force_to_append.getNumGlobalParameters()):
                    existing_force.addGlobalParameter(
                        force_to_append.getGlobalParameterName(index),
                        force_to_append.getGlobalParameterDefaultValue(index),
                    )
                for index in range(force_to_append.getNumPerBondParameters()):
                    existing_force.addPerBondParameter(
                        force_to_append.getPerBondParameterName(index)
                    )
                existing_system.addForce(existing_force)

            else:
                existing_force = type(force_to_append)()
                existing_system.addForce(existing_force)

        if isinstance(force_to_append, openmm.HarmonicBondForce):
            # Add the bonds.
            for index in range(force_to_append.getNumBonds()):
                index_a, index_b, *parameters = force_to_append.getBondParameters(
                    index
                )

                index_a = index_map[index_a]
                index_b = index_map[index_b]

                existing_force.addBond(
                    index_a + index_offset, index_b + index_offset, *parameters
                )

        elif isinstance(force_to_append, openmm.HarmonicAngleForce):
            # Add the angles.
            for index in range(force_to_append.getNumAngles()):
                (
                    index_a,
                    index_b,
                    index_c,
                    *parameters,
                ) = force_to_append.getAngleParameters(index)

                index_a = index_map[index_a]
                index_b = index_map[index_b]
                index_c = index_map[index_c]

                existing_force.addAngle(
                    index_a + index_offset,
                    index_b + index_offset,
                    index_c + index_offset,
                    *parameters,
                )

        elif isinstance(force_to_append, openmm.PeriodicTorsionForce):
            # Add the torsions.
            for index in range(force_to_append.getNumTorsions()):
                (
                    index_a,
                    index_b,
                    index_c,
                    index_d,
                    *parameters,
                ) = force_to_append.getTorsionParameters(index)

                index_a = index_map[index_a]
                index_b = index_map[index_b]
                index_c = index_map[index_c]
                index_d = index_map[index_d]

                existing_force.addTorsion(
                    index_a + index_offset,
                    index_b + index_offset,
                    index_c + index_offset,
                    index_d + index_offset,
                    *parameters,
                )

        elif isinstance(force_to_append, openmm.NonbondedForce):
            # Add the vdW parameters
            for index in range(force_to_append.getNumParticles()):
                index = index_map[index]

                existing_force.addParticle(
                    *force_to_append.getParticleParameters(index)
                )

            # Add the 1-2, 1-3 and 1-4 exceptions.
            for index in range(force_to_append.getNumExceptions()):
                (
                    index_a,
                    index_b,
                    *parameters,
                ) = force_to_append.getExceptionParameters(index)

                index_a = index_map[index_a]
                index_b = index_map[index_b]

                existing_force.addException(
                    index_a + index_offset, index_b + index_offset, *parameters
                )

        elif isinstance(force_to_append, openmm.RBTorsionForce):
            # Support for RBTorisionForce needed for OPLSAA, etc
            for index in range(force_to_append.getNumTorsions()):
                torsion_params = force_to_append.getTorsionParameters(index)
                for i in range(4):
                    torsion_params[i] = index_map[torsion_params[i]] + index_offset

                existing_force.addTorsion(*torsion_params)

        elif isinstance(force_to_append, openmm.CustomNonbondedForce):
            for index in range(force_to_append.getNumParticles()):
                nb_params = force_to_append.getParticleParameters(index_map[index])
                existing_force.addParticle(nb_params)

            # Add the 1-2, 1-3 and 1-4 exceptions.
            for index in range(force_to_append.getNumExclusions()):
                (
                    index_a,
                    index_b,
                ) = force_to_append.getExclusionParticles(index)

                index_a = index_map[index_a]
                index_b = index_map[index_b]

                existing_force.addExclusion(
                    index_a + index_offset, index_b + index_offset
                )

        elif isinstance(force_to_append, openmm.CustomBondForce):
            for index in range(force_to_append.getNumBonds()):
                index_a, index_b, bond_params = force_to_append.getBondParameters(
                    index
                )

                index_a = index_map[index_a] + index_offset
                index_b = index_map[index_b] + index_offset

                existing_force.addBond(index_a, index_b, bond_params)

        number_of_appended_forces += 1

    if number_of_appended_forces != system_to_append.getNumForces():
        raise ValueError("Not all forces were appended.")

def create_empty_system():
    system = openmm.System()
    system.addForce(openmm.HarmonicBondForce())
    system.addForce(openmm.HarmonicAngleForce())
    system.addForce(openmm.PeriodicTorsionForce())

    nonbonded_force = openmm.NonbondedForce()
    nonbonded_force.setNonbondedMethod(openmm.NonbondedForce.NoCutoff)

    system.addForce(nonbonded_force)

    return system

In [206]:
NUM_GASES = 5
NUM_TIMESTEPS = 10000

In [207]:
TEMP = to_openmm(298 * unit.kelvin)
PRESSURE = to_openmm(1 * unit.atm)
TIMESTEP = to_openmm(2 * unit.femtosecond)
GAS = Molecule.from_smiles('O=C=O')
ATOMS_PER_GAS_MOLECULE = len(GAS.atoms)
GAS_POS = np.array([
    (np.array([0, 0, 0])),
    (np.array([0.1163, 0, 0])),
    (np.array([0.2326, 0, 0]))
])  # nm
BOLTZMANN = (openmm.unit.BOLTZMANN_CONSTANT_kB * openmm.unit.AVOGADRO_CONSTANT_NA)
OPENFF_FF = ForceField("openff-2.2.0-uff.offxml", load_plugins=True)
PROB_INSERT_DELETE = 0.333
R_CUTOFF = 0.1 * unit.nanometer


In [208]:
MOF_TOP = Topology.from_molecules(mols)   
BOX_SIZE = 2.6343  # nm 
MOF_PBC = PBC(BOX_SIZE, BOX_SIZE, BOX_SIZE, 90, 90, 90)
MOF_TOP.box_vectors = np.array([[BOX_SIZE, 0, 0], [0, BOX_SIZE, 0], [0, 0, BOX_SIZE]]) * unit.nanometer
MOF_TOP.is_periodic = True

interchange = Interchange.from_smirnoff(topology=MOF_TOP, force_field=OPENFF_FF)
MOF_OPENMM_SYS = interchange.to_openmm(combine_nonbonded_forces=False)
for i in range(MOF_OPENMM_SYS.getNumParticles()):
    MOF_OPENMM_SYS.setParticleMass(i, 0.0)

In [209]:
gas_mols = [deepcopy(GAS)]
gas_top = Topology.from_molecules(gas_mols)
gas_interchange = Interchange.from_smirnoff(topology=gas_top, force_field=OPENFF_FF)
gas_openmm_sys = gas_interchange.to_openmm(combine_nonbonded_forces=False)

# openmm_sys.addForce(openmm.MonteCarloBarostat(PRESSURE, TEMP))
openmm_integrator = openmm.LangevinIntegrator(TEMP, 1, TIMESTEP)

openmm_sim = openmm.app.Simulation(gas_top.to_openmm(), gas_openmm_sys, openmm_integrator, platform=openmm.Platform.getPlatformByName("CPU"))

openmm_sim.context.setPositions(to_openmm(GAS_POS * unit.nanometer))
openmm_sim.minimizeEnergy()
context = openmm_sim.context.getState(getEnergy=True)
GAS_FORMATION_ENERGY = context.getPotentialEnergy()

In [210]:
def potential_energy(gases: np.ndarray) -> float:
    mof_openmm_sys = deepcopy(MOF_OPENMM_SYS)
    positions = deepcopy(MOF_TOP.get_positions().m)
    
    if len(gases) != 0:
        gas_mols = [deepcopy(GAS) for _ in range(len(gases) // ATOMS_PER_GAS_MOLECULE)]
        gas_top = Topology.from_molecules(gas_mols)
        gas_interchange = Interchange.from_smirnoff(topology=gas_top, force_field=OPENFF_FF)
        gas_openmm_sys = gas_interchange.to_openmm(combine_nonbonded_forces=False)
        
        # Create modeller with MOF topology and positions
        modeller = openmm.app.Modeller(MOF_TOP.to_openmm(), to_openmm(positions * unit.nanometer))
        
        # Add gas topology and positions
        gas_positions = to_openmm([x.m for x in gases] * unit.nanometer)
        modeller.add(gas_top.to_openmm(), gas_positions)
        
        # Get merged topology and positions
        merged_top = modeller.topology
        merged_positions = modeller.positions
        
        # Combine force systems
        append_system(mof_openmm_sys, gas_openmm_sys, 1 * unit.nanometer)
        
        openmm_integrator = openmm.LangevinIntegrator(TEMP, 1, TIMESTEP)
        openmm_sim = openmm.app.Simulation(merged_top, mof_openmm_sys, openmm_integrator, 
                                         platform=openmm.Platform.getPlatformByName("CPU"))
        openmm_sim.context.setPositions(merged_positions)
    else:
        openmm_integrator = openmm.LangevinIntegrator(TEMP, 1, TIMESTEP)
        openmm_sim = openmm.app.Simulation(MOF_TOP.to_openmm(), mof_openmm_sys, openmm_integrator, 
                                         platform=openmm.Platform.getPlatformByName("CPU"))
        openmm_sim.context.setPositions(to_openmm(positions * unit.nanometer))
    
    pdb_reporter = openmm.app.PDBReporter('out.pdb', 1)
    openmm_sim.reporters.append(pdb_reporter)

    openmm_sim.minimizeEnergy()
    openmm_sim.step(1)
    
    context = openmm_sim.context.getState(getEnergy=True)
    return context.getPotentialEnergy()

def run_simulation(gases: np.ndarray):
    mof_openmm_sys = deepcopy(MOF_OPENMM_SYS)
    positions = deepcopy(MOF_TOP.get_positions().m)
    
    if len(gases) != 0:
        gas_mols = [deepcopy(GAS) for _ in range(len(gases) // ATOMS_PER_GAS_MOLECULE)]
        gas_top = Topology.from_molecules(gas_mols)
        gas_interchange = Interchange.from_smirnoff(topology=gas_top, force_field=OPENFF_FF)
        gas_openmm_sys = gas_interchange.to_openmm(combine_nonbonded_forces=False)
        
        # Create modeller with MOF topology and positions
        modeller = openmm.app.Modeller(MOF_TOP.to_openmm(), to_openmm(positions * unit.nanometer))
        
        # Add gas topology and positions
        gas_positions = to_openmm([x.m for x in gases] * unit.nanometer)
        modeller.add(gas_top.to_openmm(), gas_positions)
        
        # Get merged topology and positions
        merged_top = modeller.topology
        merged_positions = modeller.positions
        
        # Combine force systems
        append_system(mof_openmm_sys, gas_openmm_sys, 1 * unit.nanometer)
        
        openmm_integrator = openmm.LangevinIntegrator(TEMP, 1, TIMESTEP)
        openmm_sim = openmm.app.Simulation(merged_top, mof_openmm_sys, openmm_integrator, 
                                         platform=openmm.Platform.getPlatformByName("CPU"))
        openmm_sim.context.setPositions(merged_positions)
    else:
        openmm_integrator = openmm.LangevinIntegrator(TEMP, 1, TIMESTEP)
        openmm_sim = openmm.app.Simulation(MOF_TOP.to_openmm(), mof_openmm_sys, openmm_integrator, 
                                         platform=openmm.Platform.getPlatformByName("CPU"))
        openmm_sim.context.setPositions(to_openmm(positions * unit.nanometer))
    
    pdb_reporter = openmm.app.PDBReporter('out.pdb', 1)
    openmm_sim.reporters.append(pdb_reporter)

    state_reporter = openmm.app.StateDataReporter(sys.stdout, 100, step=True, time=True, potentialEnergy=True, 
                                                  temperature=True, kineticEnergy=True, totalEnergy=True, 
                                                  totalSteps=NUM_TIMESTEPS, remainingTime=True, speed=True)
    openmm_sim.reporters.append(state_reporter)

    openmm_sim.minimizeEnergy()
    openmm_sim.step(NUM_TIMESTEPS)
    

def suggest_gas_position(gas_positions):
    current_pe = potential_energy(gas_positions)
    while True:
        new_pos = deepcopy(GAS_POS)
        rotation_matrix = scipy.spatial.transform.Rotation.random().as_matrix()
        shift = np.array([random.uniform(0, BOX_SIZE), random.uniform(0, BOX_SIZE), random.uniform(0, BOX_SIZE)])  # nm
        new_pos = np.dot(new_pos, rotation_matrix) + shift
        valid = True

        for atom in new_pos:
            for dim in atom:
                if dim < 0 or dim > BOX_SIZE:
                    valid = False

        superman = [x * unit.nanometer for x in new_pos]
        
        for mof_atom in MOF_TOP.get_positions():
            for gas_atom in superman:
                if MOF_PBC.min_image((mof_atom - gas_atom)) < R_CUTOFF:
                    valid = False
        
        for existing_gas in gas_positions:
            for new_gas in superman:
                if MOF_PBC.min_image((existing_gas - new_gas)) < R_CUTOFF:
                    valid = False
        
        if not valid:
            continue

        SHIFT_TOLERANCE = 0.001  # nm
        TEMP_CUTOFF = 5 * openmm.unit.kelvin * openmm.unit.BOLTZMANN_CONSTANT_kB * openmm.unit.AVOGADRO_CONSTANT_NA
        for (dx, dy, dz) in itertools.product(range(-1, 2), repeat=3):
            new_pos_shifted = [x * unit.nanometer for x in new_pos + np.array([dx, dy, dz]) * SHIFT_TOLERANCE]

            gas_pos_copy = deepcopy(gas_positions)
            gas_pos_copy.extend(new_pos_shifted)

            new_pe = potential_energy(gas_pos_copy)
            if abs(new_pe - current_pe) < TEMP_CUTOFF:
                valid = False
                break

        if not valid:
            continue
        print(new_pos)
        print(type(new_pos))
        return [x * unit.nanometer for x in new_pos]

In [211]:
random.seed(42)

gases = []  # Must be a list where elements are Quantity<[x, y, z] * unit.nanometer> coordinates
for _ in range(NUM_GASES):
    gases.extend(suggest_gas_position(gases))
    print(gases)
    
print("Gases inserted, starting simulation")

run_simulation(gases)

[[ 1.68444202  0.06588583  0.72450973]
 [ 1.77151674  0.02092694  0.66188082]
 [ 1.85859146 -0.02403195  0.59925191]]
<class 'numpy.ndarray'>
[<Quantity([1.68444202 0.06588583 0.72450973], 'nanometer')>, <Quantity([1.77151674 0.02092694 0.66188082], 'nanometer')>, <Quantity([ 1.85859146 -0.02403195  0.59925191], 'nanometer')>]
[[0.58800405 1.94008612 1.78262946]
 [0.48144784 1.97356701 1.75021812]
 [0.37489163 2.00704789 1.71780678]]
<class 'numpy.ndarray'>
[<Quantity([1.68444202 0.06588583 0.72450973], 'nanometer')>, <Quantity([1.77151674 0.02092694 0.66188082], 'nanometer')>, <Quantity([ 1.85859146 -0.02403195  0.59925191], 'nanometer')>, <Quantity([0.58800405 1.94008612 1.78262946], 'nanometer')>, <Quantity([0.48144784 1.97356701 1.75021812], 'nanometer')>, <Quantity([0.37489163 2.00704789 1.71780678], 'nanometer')>]
[[2.35026864 0.22902297 1.11146865]
 [2.25164809 0.28450384 1.13833033]
 [2.15302754 0.33998472 1.16519201]]
<class 'numpy.ndarray'>
[<Quantity([1.68444202 0.06588583 0

ValueError: coordinate "18041285995.073174" could not be represented in a width-8 field